"""Golden-file regression suite for the Arelle validation service.

Runs the *real* validator (not a stub) against the taxonomy cache bundled in
the repo, asserting the two verdicts that matter:

  - a known-valid instance validates clean (valid: true, zero errors), and
  - a known-broken instance produces a specific, pinned error.

Both run offline: validator.validate_xbrl forces internetConnectivity="offline"
and resolves against cache/, so these tests never touch the network. The
fixtures are real taxonomy-correct instances generated by the amsf_survey gem;
see tests/fixtures/README.md for provenance and how to regenerate them.

The 2025-campaign lane validates clean and broken instances fully. The 2026
lane proves the campaign-year cache addressing and per-campaign XULE ruleset
selection work end-to-end (the 2026 DTS resolves offline and the 2026 ruleset
loads and executes); the clean-verdict assertion for 2026 is xfail, tracked in
laurentqro/bos#18 (the 2026 XULE ruleset has runtime errors and spurious
conditional firing that must be fixed gem-side before a 2026 instance can
validate clean).
"""

from pathlib import Path

import pytest

from app.validator import validate_xbrl


FIXTURES = Path(__file__).parent / "fixtures"

# The sum-of-children XULE cross-field rule the broken fixture violates:
# a1101 (5) < a1102 + a1103 + a1104 + a1501 + a1802TOLA (3+2+2+2+1 = 10).
SUM_RULE_CODE = "a1101-a1102-a1103-a1104-a1501-a1802TOLA-Sum"


def _read(name):
    return (FIXTURES / name).read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def valid_result():
    return validate_xbrl(_read("valid_instance.xbrl")).to_dict()


@pytest.fixture(scope="module")
def broken_result():
    return validate_xbrl(_read("broken_instance.xbrl")).to_dict()


# --- valid instance -> clean verdict ----------------------------------------


def test_valid_instance_is_valid(valid_result):
    assert valid_result["valid"] is True


def test_valid_instance_has_zero_errors(valid_result):
    assert valid_result["summary"]["errors"] == 0


def test_valid_instance_reports_no_error_messages(valid_result):
    errors = [m for m in valid_result["messages"] if m["severity"] == "error"]
    assert errors == [], f"expected no errors, got: {[m['message'] for m in errors]}"


# --- broken instance -> specific expected error -----------------------------


def test_broken_instance_is_invalid(broken_result):
    assert broken_result["valid"] is False


def test_broken_instance_pins_the_sum_of_children_rule(broken_result):
    # Assert on the specific failure, not merely the boolean verdict, so a
    # regression that changes *which* error fires is caught. We match by both
    # the XULE rule code and identifying message text.
    matches = [
        m
        for m in broken_result["messages"]
        if m["severity"] == "error" and m["code"] == SUM_RULE_CODE
    ]
    assert len(matches) == 1, (
        f"expected exactly one {SUM_RULE_CODE} error, got "
        f"{[m['code'] for m in broken_result['messages'] if m['severity'] == 'error']}"
    )
    assert "Sum of children" in matches[0]["message"]
    assert "more than the parent" in matches[0]["message"]
    assert "a1101" in matches[0]["message"]


def test_broken_instance_reports_multiple_errors(broken_result):
    # The active-entity (aACTIVE = Oui) required-field cascade fires alongside
    # the sum rule, so the broken fixture is a substantive failure, not a
    # single trivial violation.
    assert broken_result["summary"]["errors"] > 1


# --- 2026 lane: campaign-year addressing + ruleset selection ----------------
#
# These prove the parts this slice (#17) delivers: the 2026 DTS resolves from
# the campaign-year cache directory offline, and the validator selects the 2026
# XULE ruleset (not the 2025 one, not none) from the instance's schemaRef. The
# instance is a well-formed 2026 inactive-entity submission.


@pytest.fixture(scope="module")
def instance_2026_result():
    return validate_xbrl(_read("instance_2026.xbrl")).to_dict()


def test_2026_instance_resolves_dts_offline(instance_2026_result):
    # If the campaign-year cache (strix/2026/) were missing or misaddressed,
    # Arelle would fail to load the DTS and the log would not parse into a
    # structured verdict. A populated summary proves the 2026 DTS resolved
    # offline.
    assert "summary" in instance_2026_result
    codes = {m["code"] for m in instance_2026_result["messages"]}
    assert "arelle:logParseError" not in codes


def test_2026_ruleset_is_selected_and_executes(instance_2026_result):
    # The 2026 XULE ruleset firing (its rule codes appear in the messages)
    # proves campaign-year ruleset selection works: a 2026 instance is checked
    # against strix_2026_rules.zip, not the 2025 ruleset or none. These specific
    # rule families exist only in the 2026 ruleset.
    messages = " ".join(m["code"] + m["message"] for m in instance_2026_result["messages"])
    assert "aINNUMSALES" in messages or "aNOTACTIVE" in messages, (
        "expected 2026-specific XULE rules to fire, indicating the 2026 ruleset "
        "was selected and executed"
    )


@pytest.mark.xfail(
    reason="2026 XULE ruleset has abs(none) runtime errors and spurious "
    "conditional firing; fixed gem-side in laurentqro/bos#18",
    strict=True,
)
def test_2026_instance_validates_clean(instance_2026_result):
    # The done-criterion target: a well-formed 2026 instance should validate
    # clean. It does not yet, because of ruleset defects tracked in #18. Marked
    # strict xfail so this flips to a real pass (and fails loudly) the moment
    # the ruleset is fixed.
    assert instance_2026_result["valid"] is True
    assert instance_2026_result["summary"]["errors"] == 0
